version: 2

sources:
  - name: util
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: util

    tables:
      - name: dates
        description: 'Date utility table'
      - name: world_cities
        description: 'City information (Latitude/Longitude'