version: 2

sources:
  - name: mattermost2
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: mattermost2

    tables: 
      - name: server
        description: 'Daily server data'
    
      - name: license
        description: 'Daily license data'