version: 2

sources:
  - name: ga_channelgrouping_source_users_org
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_channelgroupingsource_users_org

    tables: 
      - name: report
        description: 'Users visiting Mattermost.org by Source and Channel Grouping'

  - name: ga_channelgrouping_source_users_com
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: ga_channelgroupingsource_users_com

    tables: 
      - name: report
        description: 'Users visiting Mattermost.com by Source and Channel Grouping'