version: 2

sources:
  - name: zendesk_raw
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: zendesk_raw

    tables: 
      - name: tickets
        description: 'Zendesk Tickets'
      - name: organizations
        description: 'Zendesk Organizations (maps one to one with SFDC Accounts)'
      - name: sla_policies
        description: 'Zendesk SLA Policies'
      - name: tags
        description: 'Zendesk Tags'
      - name: ticket_audits
        description: 'Zendesk Ticket Audits'
      - name: ticket_comments
        description: 'Zendesk Ticket Comments'
      - name: ticket_forms
        description: 'Zendesk Ticket Forms'
      - name: ticket_fields
        description: 'Zendesk Ticket Fields'
      - name: ticket_metrics
        description: 'Zendesk Ticket Metrics'
      - name: ticket_users
        description: 'Zendesk Users'
      - name: satisfaction_ratings
        description: 'Zendesk Satisfaction Ratings'