version: 2

models:
  - name: server_daily_details
    description: Production server daily details table. Derived from event.security. Only includes production servers defined in TEDAS logic.
    columns:
      - name: server_id
        tests:
          - not_null

  - name: downloads
    description: Mattermost downloads
  
  - name: contributor_employee_map_data
    description: Location data on contributors and employees

  - name: github_contributors
    description: Statistics on GitHub contributors
  
  - name: nps_data
    description: NPS scores and feedback