version: 2

models:
  - name: server_daily_details
    description: Server daily details
    columns:
      - name: server_id
        tests:
          - not_null

  - name: downloads
    description: Mattermost downloads
  
  - name: contributor_employee_map_data
    description: Location data on contributors and employees