version: 2

sources:
  - name: mattermost
    database: '{{ env_var("SNOWFLAKE_TRANSFORM_DATABASE") }}'
    schema: mattermost

    tables: 
      - name: github_contributions
  
  - name: licenses
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: licenses