version: 2

models:
  - name: mattermost2_server_staging
    description: Contains cleaned version of raw.mattermost2.server table by retreiving the row with the most recent timestamp for a server_id on a given day. 1 row per server per day.
  
  - name: events_security_staging
    description: Contains cleaned version of analytics.events.security table by retrieving row with max active user count for a server_id on a given day. 1 row per server per day.