version: 2
models:
  - name: orgm_account_data_check
    description: OrgM Account data sent to Heroku Postgres to confirm data integrity
      across systems.
  - name: orgm_opportunity_data_check
    description: OrgM Opportunity data sent to Heroku Postgres to confirm data
      integrity across systems.
  - name: orgm_opportunitylineitem_data_check
    description: OrgM Opportunity Line Item data sent to Heroku Postgres to confirm
      data integrity across systems.
  - name: orgm_account_arr_and_seats
    description: Current Account ARR & Licensed Seats
    meta:
      hightouch:
        model:
          id: 1094
        destinations:
          - id: 52590
            config:
              mode: update
              fromId: ACCOUNT_SFID
              object: Account
              mappings:
                - to: ARR_Current__c
                  from: TOTAL_ARR
                - to: Seats_Licensed__c
                  from: SEATS
            schedule:
              type: manual
